name: multipart_request
description: A flutter plugin to send a multipart request and get stream of progress.
version: 0.1.1
author: Aawaz Gyawali <awazgyawali@gmail.com>
homepage: https://github.com/awazgyawali/multipart_request

environment:
  sdk: ">=2.12.0 <3.6.0"

dependencies:
  flutter:
    sdk: flutter


flutter:
  plugin:
    androidPackage: com.brainants.multipartrequest
    pluginClass: MultipartRequestPlugin
